apiVersion: v1
kind: Pod
metadata:
  labels:
    run: fox
  name: fox
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /fox
      name: emptydir-1
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
    args:
    - sleep
    - "1800"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: emptydir-1
    emptyDir:
      sizeLimit: 256Mi
