apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lion
  name: lion
spec:
  containers:
  - image: nginx
    name: lion
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
